services:
  product-service:
    container_name: product-api
    build: .
    ports:
      - "8080:8080"

  price-service:
    container_name: price-api
    build: ../api2/
    ports:
      - "8082:8082"

  jaeger-service:
    image: jaegertracing/all-in-one:latest
    container_name: jaeger
    ports:
      - "16686:16686"
      - "4318:4318"
    environment:
      - COLLECTOR_OTLP_ENABLED=true