services:
  product-service:
    container_name: product-api
    build: .
    ports:
      - "8080:8080"

  price-service:
    container_name: price-api
    build: ../api2/
    ports:
      - "8082:8082"

  collector:
    image: otel/opentelemetry-collector:0.72.0
    container_name: collector
    command: [ "--config=/etc/otel-collector-config.yml" ]
    volumes:
      - ./otel-config.yml:/etc/otel-collector-config.yml
    ports:
      - "4317:4317"
    depends_on:
      - jaeger-service

  jaeger-service:
    image: jaegertracing/all-in-one:latest
    container_name: jaeger
    ports:
      - "16686:16686"
      - "4318:4318"
    environment:
      - COLLECTOR_OTLP_ENABLED=true