spring:
  application:
    name: rest-api

  sleuth:
    otel:
      config:
        trace-id-ratio-based: 1.0
      exporter:
        otlp:
          endpoint: http://collector:4317
server:
  port : 8080
  servlet:
    context-path: /rest-api