spring:
  application:
    name: rest-api
server:
  port : 8080
  servlet:
    context-path: /rest-api

management:
  tracing:
    sampling:
      probability: 1.0

tracing:
#  jaeger url
  url: http://localhost:4318/v1/traces

logging:
  pattern:
    level: '%5p [${spring.application.name:},%X{traceId:-},%X{spanId:-}]'